# Generated by Django 6.0.6 on 2026-07-05 19:42

import apps.common.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0002_alter_bid_delivery_days_alter_bid_proposed_price'),
        ('design_requests', '0002_designrequest_color_preferences_and_more'),
        ('vendors', '0002_vendorprofile_avg_rating_vendorprofile_review_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('current_stage', models.CharField(choices=[('sourcing', 'Fabric Sourced'), ('cutting', 'Cutting'), ('sewing', 'Sewing'), ('quality_check', 'Quality Check'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='sourcing', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='bids.bid')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='design_requests.designrequest')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vendors.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('sourcing', 'Fabric Sourced'), ('cutting', 'Cutting'), ('sewing', 'Sewing'), ('quality_check', 'Quality Check'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='production_updates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.common.validators.validate_image_size, apps.common.validators.validate_image_dimensions])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_updates', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_updates', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
