# Generated by Django 6.0.6 on 2026-07-05 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('apparel_type', models.CharField(choices=[('hoodie', 'Hoodie'), ('jacket', 'Jacket'), ('tshirt', 'T-Shirt'), ('football_kit', 'Football Kit'), ('other', 'Other')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('material', models.CharField(blank=True, max_length=255)),
                ('design_image', models.ImageField(blank=True, null=True, upload_to='design_requests/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('awarded', 'Awarded'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
