# Generated by Django 6.0.6 on 2026-07-05 19:42

import apps.common.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='color_preferences',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='sizes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='design_requests/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.common.validators.validate_image_size, apps.common.validators.validate_image_dimensions]),
        ),
        migrations.CreateModel(
            name='DesignReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='design_requests/references/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.common.validators.validate_image_size, apps.common.validators.validate_image_dimensions])),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='design_requests.designrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
